# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bbba308e2e815b829f5fb6d170d512d48ec6e0f233314a030a573b4db75d46f4258bcc80975ceb6795f0e4bb2abeaea6f6882959eb23d57a05c46c02af4c836a

test:
  secret_key_base: 8680d948993ebc19ed4c842a5e54b7be432aff4c8e2b947e7bd10bd1f830d450d0f64e3af9eb62a02aa26cc605ecf4a99c26baa064533f18a25ffa020f540bdc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
